import { MenuItem, Order, Offer, Testimonial, Location, FAQ, BlogPost, CareerPosition, GalleryImage } from './types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Margherita',
    description: 'Fresh mozzarella, basil, and tomato sauce on our signature crust',
    category: 'Pizza',
    price: 12.99,
    image: '/images/margherita.jpg',
    available: true,
    prepTime: 15,
    spicy: false,
    vegetarian: true,
    vegan: false,
  },
  {
    id: '2',
    name: 'Pepperoni',
    description: 'Classic pepperoni with mozzarella cheese and tomato sauce',
    category: 'Pizza',
    price: 14.99,
    image: '/images/pepperoni.jpg',
    available: true,
    prepTime: 15,
    spicy: true,
    vegetarian: false,
    vegan: false,
  },
  {
    id: '3',
    name: 'Quattro Formaggi',
    description: 'A blend of four cheeses: mozzarella, parmesan, gorgonzola, and ricotta',
    category: 'Pizza',
    price: 15.99,
    image: '/images/quattro.jpg',
    available: true,
    prepTime: 16,
    spicy: false,
    vegetarian: true,
    vegan: false,
  },
  {
    id: '4',
    name: 'Spicy Italian',
    description: 'Pepperoni, jalapeños, red onions, and spicy sauce',
    category: 'Pizza',
    price: 15.99,
    image: '/images/spicy.jpg',
    available: true,
    prepTime: 15,
    spicy: true,
    vegetarian: false,
    vegan: false,
  },
  {
    id: '5',
    name: 'Vegetarian Delight',
    description: 'Bell peppers, mushrooms, olives, tomatoes, and fresh basil',
    category: 'Pizza',
    price: 13.99,
    image: '/images/veggie.jpg',
    available: true,
    prepTime: 15,
    spicy: false,
    vegetarian: true,
    vegan: true,
  },
  {
    id: '6',
    name: 'Garlic Bread',
    description: 'Crispy bread with garlic butter and herbs',
    category: 'Appetizer',
    price: 4.99,
    image: '/images/garlic-bread.jpg',
    available: true,
    prepTime: 8,
    spicy: false,
    vegetarian: true,
    vegan: false,
  },
  {
    id: '7',
    name: 'Bruschetta',
    description: 'Toasted bread with fresh tomatoes, basil, and garlic',
    category: 'Appetizer',
    price: 6.99,
    image: '/images/bruschetta.jpg',
    available: true,
    prepTime: 10,
    spicy: false,
    vegetarian: true,
    vegan: true,
  },
  {
    id: '8',
    name: 'Calamari Fritti',
    description: 'Crispy fried squid with marinara sauce',
    category: 'Appetizer',
    price: 8.99,
    image: '/images/calamari.jpg',
    available: true,
    prepTime: 12,
    spicy: false,
    vegetarian: false,
    vegan: false,
  },
  {
    id: '9',
    name: 'Pasta Carbonara',
    description: 'Creamy pasta with pancetta, eggs, and parmesan',
    category: 'Pasta',
    price: 14.99,
    image: '/images/carbonara.jpg',
    available: true,
    prepTime: 20,
    spicy: false,
    vegetarian: false,
    vegan: false,
  },
  {
    id: '10',
    name: 'Pasta Primavera',
    description: 'Fresh seasonal vegetables with olive oil and garlic',
    category: 'Pasta',
    price: 12.99,
    image: '/images/primavera.jpg',
    available: true,
    prepTime: 18,
    spicy: false,
    vegetarian: true,
    vegan: true,
  },
  {
    id: '11',
    name: 'Lasagna Bolognese',
    description: 'Layered pasta with meat sauce and melted mozzarella',
    category: 'Pasta',
    price: 13.99,
    image: '/images/lasagna.jpg',
    available: true,
    prepTime: 25,
    spicy: false,
    vegetarian: false,
    vegan: false,
  },
  {
    id: '12',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce, parmesan, croutons, and caesar dressing',
    category: 'Salad',
    price: 9.99,
    image: '/images/caesar.jpg',
    available: true,
    prepTime: 8,
    spicy: false,
    vegetarian: true,
    vegan: false,
  },
  {
    id: '13',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with mascarpone and espresso',
    category: 'Dessert',
    price: 6.99,
    image: '/images/tiramisu.jpg',
    available: true,
    prepTime: 5,
    spicy: false,
    vegetarian: true,
    vegan: false,
  },
  {
    id: '14',
    name: 'Panna Cotta',
    description: 'Smooth Italian cream dessert with berry compote',
    category: 'Dessert',
    price: 6.99,
    image: '/images/panna-cotta.jpg',
    available: true,
    prepTime: 5,
    spicy: false,
    vegetarian: true,
    vegan: false,
  },
  {
    id: '15',
    name: 'Coca Cola',
    description: 'Cold soft drink',
    category: 'Beverage',
    price: 2.99,
    image: '/images/cola.jpg',
    available: true,
    prepTime: 2,
    spicy: false,
    vegetarian: true,
    vegan: true,
  },
  {
    id: '16',
    name: 'Italian Red Wine',
    description: 'Premium red wine from Tuscany',
    category: 'Beverage',
    price: 8.99,
    image: '/images/wine.jpg',
    available: true,
    prepTime: 2,
    spicy: false,
    vegetarian: true,
    vegan: true,
  },
];

export const offers: Offer[] = [
  {
    id: '1',
    title: 'Friday Special',
    description: 'Get 20% off on all pizzas every Friday',
    discount: 20,
    discountType: 'percentage',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2025-12-31'),
    applicableItems: ['1', '2', '3', '4', '5'],
    active: true,
  },
  {
    id: '2',
    title: 'Family Bundle',
    description: 'Buy 2 large pizzas and get appetizers at 50% off',
    discount: 50,
    discountType: 'percentage',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2025-12-31'),
    minOrderAmount: 30,
    active: true,
  },
  {
    id: '3',
    title: 'Early Bird Special',
    description: 'Free dessert with orders placed before 6 PM',
    discount: 6.99,
    discountType: 'fixed',
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2025-12-31'),
    code: 'EARLYBIRD',
    active: true,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    customerName: 'Sarah Johnson',
    content: 'The best pizza I\'ve had in years! The crust is perfectly crispy and the toppings are so fresh.',
    rating: 5,
    featured: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    customerName: 'Michael Chen',
    content: 'Amazing service and the pasta is absolutely delicious. Definitely coming back!',
    rating: 5,
    featured: true,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    customerName: 'Emma Rodriguez',
    content: 'The atmosphere is wonderful and the staff is very friendly. Highly recommend!',
    rating: 5,
    featured: true,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: '4',
    customerName: 'David Park',
    content: 'Great quality ingredients and attention to detail. Worth every penny!',
    rating: 4,
    featured: false,
    createdAt: new Date('2024-02-10'),
  },
];

export const locations: Location[] = [
  {
    id: '1',
    name: 'Main Location',
    address: '476 Beach Rd, Hamilton ON L8H 3K7, Canada',
    phone: '(905) 545-8899',
    email: 'info@mamasam.com',
    hours: {
      Monday: { open: '11:00 AM', close: '10:00 PM' },
      Tuesday: { open: '11:00 AM', close: '10:00 PM' },
      Wednesday: { open: '11:00 AM', close: '10:00 PM' },
      Thursday: { open: '11:00 AM', close: '10:00 PM' },
      Friday: { open: '11:00 AM', close: '11:00 PM' },
      Saturday: { open: '12:00 PM', close: '11:00 PM' },
      Sunday: { open: '12:00 PM', close: '10:00 PM' },
    },
    latitude: 43.2505,
    longitude: -79.8000,
    image: '/images/location-downtown.jpg',
  },
];

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'How long does delivery take?',
    answer: 'Delivery typically takes 30-45 minutes depending on your location and current order volume.',
    category: 'Delivery',
    order: 1,
  },
  {
    id: '2',
    question: 'Do you offer vegetarian options?',
    answer: 'Yes! We have a variety of vegetarian and vegan pizza options available.',
    category: 'Menu',
    order: 2,
  },
  {
    id: '3',
    question: 'Can I modify my order after placing it?',
    answer: 'You can modify your order within 5 minutes of placing it. Please call us immediately if needed.',
    category: 'Orders',
    order: 3,
  },
  {
    id: '4',
    question: 'What is your cancellation policy?',
    answer: 'Orders can be cancelled within 10 minutes of placement for a full refund.',
    category: 'Policies',
    order: 4,
  },
  {
    id: '5',
    question: 'Do you accept dietary restrictions?',
    answer: 'Absolutely! We accommodate allergies and dietary preferences. Please mention them when ordering.',
    category: 'Menu',
    order: 5,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Art of Pizza Making: Our Story',
    excerpt: 'Discover how Mama Sam brings traditional Italian pizza-making techniques to every pie.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    image: '/images/blog-pizza-art.jpg',
    author: 'Mama Sam',
    featured: true,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '2',
    title: 'Fresh Ingredients Matter: Our Sourcing',
    excerpt: 'Learn about our commitment to sourcing the finest, freshest ingredients.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    image: '/images/blog-ingredients.jpg',
    author: 'Chef Antonio',
    featured: true,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '3',
    title: 'Perfect Wine Pairings for Your Pizza',
    excerpt: 'Tips on choosing the right wine to complement your favorite pizza.',
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    image: '/images/blog-wine.jpg',
    author: 'Sommelier Maria',
    featured: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

export const careerPositions: CareerPosition[] = [
  {
    id: '1',
    title: 'Pizza Chef',
    location: 'Downtown Location',
    description: 'We\'re looking for an experienced pizza chef to join our team. Must have 3+ years of pizza-making experience.',
    requirements: ['3+ years pizza-making experience', 'Knowledge of Italian cuisine', 'Team player'],
    benefits: ['Competitive salary', 'Free meals', 'Health insurance'],
    postedDate: new Date('2024-01-30'),
    featured: true,
  },
  {
    id: '2',
    title: 'Delivery Driver',
    location: 'All Locations',
    description: 'Looking for reliable delivery drivers to join our team. Must have valid driver\'s license and own vehicle.',
    requirements: ['Valid driver\'s license', 'Own vehicle', 'GPS navigation'],
    benefits: ['Competitive pay', 'Mileage reimbursement', 'Flexible schedule'],
    postedDate: new Date('2024-02-05'),
    featured: false,
  },
  {
    id: '3',
    title: 'Front Desk Staff',
    location: 'Westside Location',
    description: 'Help us welcome our customers! We need friendly and efficient front desk staff.',
    requirements: ['Customer service experience', 'Communication skills', 'Cash handling'],
    benefits: ['Competitive salary', 'Employee discounts', 'Growth opportunities'],
    postedDate: new Date('2024-02-10'),
    featured: false,
  },
];

export const galleryImages: GalleryImage[] = [
  {
    id: '1',
    title: 'Wood-Fired Oven',
    image: '/images/gallery-oven.jpg',
    category: 'restaurant',
    featured: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    title: 'Fresh Pizza',
    image: '/images/gallery-pizza.jpg',
    category: 'food',
    featured: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    title: 'Team at Work',
    image: '/images/gallery-team.jpg',
    category: 'team',
    featured: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    title: 'Sunday Family Dinner',
    image: '/images/gallery-event.jpg',
    category: 'event',
    featured: true,
    createdAt: new Date('2024-01-01'),
  },
];

// Sample orders for admin
export const sampleOrders: Order[] = [
  {
    id: 'ORD-001',
    customerName: 'John Doe',
    customerEmail: 'john@example.com',
    customerPhone: '(555) 111-2222',
    items: [
      {
        id: 'cart-1',
        menuItemId: '1',
        quantity: 2,
        price: 12.99,
      },
    ],
    totalAmount: 25.98,
    status: 'delivered',
    orderType: 'delivery',
    deliveryAddress: '123 Oak Street',
    createdAt: new Date('2024-02-15'),
    estimatedTime: 35,
  },
];
